apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
  name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        command:
        - '/bin/sh'
        - '-c'
        args:
        - |
          echo ok > /usr/share/nginx/html/healthz
          cat <<'EOF'> /etc/nginx/conf.d/default.conf
          server_tokens off;
          server {
            listen 80;
            server_name _;
            location =/healthz {
              root /usr/share/nginx/html/;
              if ( $http_user_agent ~* "ELB-HealthChecker" ) { access_log off; }
              if ( $http_user_agent ~* "kube-probe" ) { access_log off; }
              if ( $remote_addr ~* "127.0.0.1" ) { access_log off; }
            }
            location =/ {
              default_type text/plain;
              expires -1;
              return 200 'Client address: $remote_addr $http_x_forwarded_for\nServer address: $server_addr:$server_port\nServer name: $hostname\nDate: $time_local\nHost: $host\nURI: $request_uri\nRequest ID: $request_id\n';
            }
          }
          EOF
          exec nginx -g 'daemon off;'
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1

---        
apiVersion: v1
kind: Service
metadata:
  labels:
    app: whoami
  name: whoami
spec:
  selector:
    app: whoami
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
